### ISSUE TITLE
Breaks in Sprockets 3

### ISSUE THREAD

**Issue by outdooricon** [simplificator/asset_pipeline_i18n#3]
When I run assets:precompile, I get

``` ruby
NoMethodError: undefined method `clear' for nil:NilClass
asset_pipeline_i18n-4.0.1.2/lib/asset_pipeline_i18n/railtie.rb:44:in `fixup_cache'
asset_pipeline_i18n-4.0.1.2/lib/asset_pipeline_i18n/railtie.rb:26:in `block (4 levels) in define'
sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in `with_logger'
asset_pipeline_i18n-4.0.1.2/lib/asset_pipeline_i18n/railtie.rb:25:in `block (3 levels) in define'
asset_pipeline_i18n-4.0.1.2/lib/asset_pipeline_i18n/railtie.rb:22:in `each'
asset_pipeline_i18n-4.0.1.2/lib/asset_pipeline_i18n/railtie.rb:22:in `block (2 levels) in define'`
```

**Comment by gucki** [comment]
Please post your full Gemfile.lock. Thanks.

**Comment by outdooricon** [comment]
Mind if I email it to you at info@corinlangosch.com?

**Comment by outdooricon** [comment]
Sent to that email address. Thanks!

**Comment by outdooricon** [comment]
Did you receive it?
